pipeline:

  build-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t hocs-management-ui .
    when:
      event: push

  install-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag hocs-management-ui quay.io/ukhomeofficedigital/hocs-management-ui:build-$${DRONE_BUILD_NUMBER}
      - docker tag hocs-management-ui quay.io/ukhomeofficedigital/hocs-management-ui:latest
      - docker push quay.io/ukhomeofficedigital/hocs-management-ui:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/hocs-management-ui:latest
    when:
      event: push

  docker-semver-tag:
    image: quay.io/ukhomeofficedigital/hocs-version-bot:build-25
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_API_VERSION=1.37
    secrets:
      - github_password
      - docker_password
      - git_password
    commands:
      - /app/hocs-deploy --version=$${SEMVER} --serviceGitToken=$${GIT_PASSWORD} --service=hocs-management-ui --gitToken=$${GITHUB_PASSWORD} --gitRepo="https://gitlab.digital.homeoffice.gov.uk/hocs/hocs-versions.git" --environment=qa --dockerRepository=quay.io/ukhomeofficedigital --sourceBuild=$${IMAGE_VERSION} --registryUser=ukhomeofficedigital+hocs --registryPassword=$${DOCKER_PASSWORD}
    when:
      event: deployment
      environment: qa

  clone-kube-project:
    image: plugins/git
    commands:
      - git clone -b master --single-branch https://github.com/UKHomeOffice/kube-hocs-management-ui.git
    when:
      event: [push, deployment, tag]

  deploy-to-cs-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v1.12.2
    environment:
      - KUBE_NAMESPACE=cs-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_management_ui_dev
    commands:
      - cd kube-hocs-management-ui
      - ./deploy.sh
    when:
      branch: [master, dev]
      event: [push, tag]

  deploy-to-wcs-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v1.12.2
    environment:
      - KUBE_NAMESPACE=wcs-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_management_ui_dev
    commands:
      - cd kube-hocs-management-ui
      - ./deploy.sh
    when:
      branch: [master, dev]
      event: [push, tag]

  deployment:
    image: quay.io/ukhomeofficedigital/kd:v1.12.2
    environment:
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_management_ui_dev
      - hocs_management_ui_demo
    commands:
      - cd kube-hocs-management-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: [dev, demo]

  deploy-to-qa:
    image: quay.io/ukhomeofficedigital/kd:v1.12.2
    environment:
      - ENVIRONMENT=qa
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_management_ui_qa
    commands:
      - source version.txt
      - echo $VERSION
      - cd kube-hocs-management-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: qa

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:v1.12.2
    environment:
      - ENVIRONMENT=prod
      - VERSION=${IMAGE_VERSION}
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
    secrets:
      - hocs_management_ui_prod
    commands:
      - cd kube-hocs-management-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: prod


