pipeline:

  build-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t hocs-management-ui .
    when:
      event: push

  install-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag hocs-management-ui quay.io/ukhomeofficedigital/hocs-management-ui:build-$${DRONE_BUILD_NUMBER}
      - docker tag hocs-management-ui quay.io/ukhomeofficedigital/hocs-management-ui:latest
      - docker push quay.io/ukhomeofficedigital/hocs-management-ui:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/hocs-management-ui:latest
    when:
      event: push

  clone-kube-project:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/kube-hocs-management-ui.git
    when:
      event: [push, deployment, tag]

  deploy-to-qa:
    image: quay.io/ukhomeofficedigital/kd:v1.12.1
    environment:
      - KUBE_NAMESPACE=cs-qa
      - ENVIRONMENT=qa
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_management_ui_qa
    commands:
      - source version.txt
      - echo $VERSION
      - cd kube-hocs-management-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: qa

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
      - KUBE_NAMESPACE=cs-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_management_ui_dev
    commands:
      - cd kube-hocs-management-ui
      - ./deploy.sh
    when:
      branch: [master, dev]
      event: [push, tag]

  deployment:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
      - KUBE_NAMESPACE=cs-${DRONE_DEPLOY_TO}
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_management_ui_dev
      - hocs_management_ui_demo
    commands:
      - cd kube-hocs-management-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: [dev, demo]

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
      - KUBE_NAMESPACE=cs-prod
      - ENVIRONMENT=prod
      - VERSION=${IMAGE_VERSION}
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
    secrets:
      - hocs_management_ui_prod
    commands:
      - cd kube-hocs-management-ui
      - ./deploy.sh
    when:
      event: deployment
      environment: prod


